version: "3"

services:
  testnet:
    build:
      context: ../packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    ports:
      - "5000:5000"
    command: ganache-cli --db=/data -i 20200406 -p 5000 --deterministic -b 14 --host 0.0.0.0
  coordinator:
    build:
      context: ../
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - "8888:8888"
      - "1234:1234"
    links:
      - 'testnet:testnet'
    depends_on:
      - 'testnet'
    volumes:
      - '../packages:/proj/packages'
    command: sh -c "sleep 5s && gotty -w --port 1234 node /proj/packages/cli/dist/apps/coordinator/cli.js --config /proj/packages/cli/coordinator.dev.json"
  wallet:
    build:
      context: ../
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - "4321:4321"
    links:
      - 'testnet:testnet'
      - 'coordinator:coordinator'
    depends_on:
      - 'testnet'
    volumes:
      - '../packages:/proj/packages'
    command: sh -c "sleep 5s && gotty -w --port 4321 node /proj/packages/cli/dist/apps/wallet/cli.js --config /proj/packages/cli/wallet.dev.json"
