/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class Coordinatable extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)
  clone(): Coordinatable
  methods: {
    CHALLENGE_LIMIT(): TransactionObject<string>

    CHALLENGE_PERIOD(): TransactionObject<string>

    MINIMUM_STAKE(): TransactionObject<string>

    POOL_SIZE(): TransactionObject<string>

    REF_DEPTH(): TransactionObject<string>

    SUB_TREE_DEPTH(): TransactionObject<string>

    SUB_TREE_SIZE(): TransactionObject<string>

    register(): TransactionObject<void>

    deregister(): TransactionObject<void>

    propose(arg0: string | number[]): TransactionObject<void>

    finalize(arg0: string | number[]): TransactionObject<void>

    withdrawReward(amount: number | string): TransactionObject<void>

    isProposable(proposerAddr: string): TransactionObject<boolean>
  }
  events: {
    Finalized: ContractEvent<string>
    MassDepositCommit: ContractEvent<{
      id: string
      merged: string
      fee: string
      0: string
      1: string
      2: string
    }>
    NewProposal: ContractEvent<string>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
