/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export type Approval = ContractEventLog<{
  owner: string
  approved: string
  tokenId: string
  0: string
  1: string
  2: string
}>
export type ApprovalForAll = ContractEventLog<{
  owner: string
  operator: string
  approved: boolean
  0: string
  1: string
  2: boolean
}>
export type Transfer = ContractEventLog<{
  from: string
  to: string
  tokenId: string
  0: string
  1: string
  2: string
}>

export interface ERC721 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ERC721
  clone(): ERC721
  methods: {
    /**
     * See {IERC165-supportsInterface}. Time complexity O(1), guaranteed to always use less than 30 000 gas.
     */
    supportsInterface(
      interfaceId: string | number[],
    ): NonPayableTransactionObject<boolean>

    /**
     * See {IERC721-balanceOf}.
     */
    balanceOf(owner: string): NonPayableTransactionObject<string>

    /**
     * See {IERC721-ownerOf}.
     */
    ownerOf(tokenId: number | string | BN): NonPayableTransactionObject<string>

    /**
     * See {IERC721Metadata-name}.
     */
    name(): NonPayableTransactionObject<string>

    /**
     * See {IERC721Metadata-symbol}.
     */
    symbol(): NonPayableTransactionObject<string>

    /**
     * See {IERC721Metadata-tokenURI}.
     */
    tokenURI(tokenId: number | string | BN): NonPayableTransactionObject<string>

    /**
     * Returns the base URI set via {_setBaseURI}. This will be automatically added as a prefix in {tokenURI} to each token's URI, or to the token ID if no specific URI is set for that token ID.
     */
    baseURI(): NonPayableTransactionObject<string>

    /**
     * See {IERC721Enumerable-tokenOfOwnerByIndex}.
     */
    tokenOfOwnerByIndex(
      owner: string,
      index: number | string | BN,
    ): NonPayableTransactionObject<string>

    /**
     * See {IERC721Enumerable-totalSupply}.
     */
    totalSupply(): NonPayableTransactionObject<string>

    /**
     * See {IERC721Enumerable-tokenByIndex}.
     */
    tokenByIndex(
      index: number | string | BN,
    ): NonPayableTransactionObject<string>

    /**
     * See {IERC721-approve}.
     */
    approve(
      to: string,
      tokenId: number | string | BN,
    ): NonPayableTransactionObject<void>

    /**
     * See {IERC721-getApproved}.
     */
    getApproved(
      tokenId: number | string | BN,
    ): NonPayableTransactionObject<string>

    /**
     * See {IERC721-setApprovalForAll}.
     */
    setApprovalForAll(
      operator: string,
      approved: boolean,
    ): NonPayableTransactionObject<void>

    /**
     * See {IERC721-isApprovedForAll}.
     */
    isApprovedForAll(
      owner: string,
      operator: string,
    ): NonPayableTransactionObject<boolean>

    /**
     * See {IERC721-transferFrom}.
     */
    transferFrom(
      from: string,
      to: string,
      tokenId: number | string | BN,
    ): NonPayableTransactionObject<void>

    /**
     * See {IERC721-safeTransferFrom}.
     */
    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: number | string | BN,
    ): NonPayableTransactionObject<void>

    /**
     * See {IERC721-safeTransferFrom}.
     */
    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: number | string | BN,
      _data: string | number[],
    ): NonPayableTransactionObject<void>
  }
  events: {
    Approval(cb?: Callback<Approval>): EventEmitter
    Approval(options?: EventOptions, cb?: Callback<Approval>): EventEmitter

    ApprovalForAll(cb?: Callback<ApprovalForAll>): EventEmitter
    ApprovalForAll(
      options?: EventOptions,
      cb?: Callback<ApprovalForAll>,
    ): EventEmitter

    Transfer(cb?: Callback<Transfer>): EventEmitter
    Transfer(options?: EventOptions, cb?: Callback<Transfer>): EventEmitter

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
  }

  once(event: 'Approval', cb: Callback<Approval>): void
  once(event: 'Approval', options: EventOptions, cb: Callback<Approval>): void

  once(event: 'ApprovalForAll', cb: Callback<ApprovalForAll>): void
  once(
    event: 'ApprovalForAll',
    options: EventOptions,
    cb: Callback<ApprovalForAll>,
  ): void

  once(event: 'Transfer', cb: Callback<Transfer>): void
  once(event: 'Transfer', options: EventOptions, cb: Callback<Transfer>): void
}
