/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IBurnAuction extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IBurnAuction

  methods: {
    transferBalance(recipient: string): TransactionObject<void>

    register(): TransactionObject<void>

    setUrl(url: string): TransactionObject<void>

    clearUrl(): TransactionObject<void>

    coordinatorUrls(url: string): TransactionObject<string>

    bid(roundIndex: number | string): TransactionObject<void>

    minNextBid(roundIndex: number | string): TransactionObject<string>

    coordinatorForRound(roundIndex: number | string): TransactionObject<string>

    activeCoordinator(): TransactionObject<string>

    currentRound(): TransactionObject<string>

    shouldOpenRound(): TransactionObject<boolean>

    isRoundOpen(): TransactionObject<boolean>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
