/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IConfigurable extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IConfigurable

  methods: {
    setMaxBlockSize(blockSize: number | string): TransactionObject<void>

    setMaxValidationGas(maxGas: number | string): TransactionObject<void>

    setChallengePeriod(period: number | string): TransactionObject<void>

    setMinimumStake(stake: number | string): TransactionObject<void>

    setReferenceDepth(depth: number | string): TransactionObject<void>

    setConsensusProvider(provider: string): TransactionObject<void>
  }

  events: {
    Update: ContractEvent<{
      name: string
      value: string
      0: string
      1: string
    }>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
