/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IERC721Receiver extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IERC721Receiver

  methods: {
    onERC721Received(
      operator: string,
      from: string,
      tokenId: number | string,
      data: string | number[],
    ): TransactionObject<string>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
