/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IHeaderValidator extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IHeaderValidator

  methods: {
    validateDepositRoot(
      blockData: string | number[],
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateTxRoot(
      blockData: string | number[],
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateMigrationRoot(
      blockData: string | number[],
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateTotalFee(
      blockData: string | number[],
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateParentBlock(
      blockData: string | number[],
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
