/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IMigrationChallenge extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IMigrationChallenge

  methods: {
    challengeDuplicatedDestination(
      destination: string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeTotalEth(
      migrationIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeMergedLeaves(
      migrationIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeMigrationFee(
      migrationIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeDuplicatedERC20Migration(
      destination: string,
      erc20: string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeERC20Amount(
      migrationIndex: number | string,
      erc20Index: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeDuplicatedERC721Migration(
      migrationIndex: number | string,
      erc20Address: string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeNonFungibility(
      migrationIndex: number | string,
      erc721Index: number | string,
      tokenId: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeNftExistence(
      migrationIndex: number | string,
      erc721Index: number | string,
      tokenId: number | string,
      blockData: string | number[],
    ): TransactionObject<void>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
