/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IMigrationValidator extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IMigrationValidator

  methods: {
    validateDuplicatedDestination(
      blockData: string | number[],
      massMigrationIdx1: number | string,
      massMigrationIdx2: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateTotalEth(
      blockData: string | number[],
      migrationIndex: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateMergedLeaves(
      blockData: string | number[],
      migrationIndex: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateMigrationFee(
      blockData: string | number[],
      migrationIndex: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateDuplicatedERC20Migration(
      blockData: string | number[],
      migrationIndex: number | string,
      erc20MigrationIdx1: number | string,
      erc20MigrationIdx2: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateERC20Amount(
      blockData: string | number[],
      migrationIndex: number | string,
      erc20Index: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateDuplicatedERC721Migration(
      blockData: string | number[],
      migrationIndex: number | string,
      erc721MigrationIdx1: number | string,
      erc721MigrationIdx2: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateNonFungibility(
      blockData: string | number[],
      migrationIndex: number | string,
      erc721Index: number | string,
      tokenId: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateNftExistence(
      blockData: string | number[],
      migrationIndex: number | string,
      erc721Index: number | string,
      tokenId: number | string,
    ): TransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
