/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IRollUpChallenge extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): IRollUpChallenge;
  methods: {
    challengeUTXORollUp(
      proofId: number | string,
      deposits: (number | string)[],
      numOfUTXO: number | string,
      submission: string | number[]
    ): TransactionObject<void>;

    challengeNullifierRollUp(
      proofId: number | string,
      numOfNullifiers: number | string,
      submission: string | number[]
    ): TransactionObject<void>;

    challengeWithdrawalRollUp(
      proofId: number | string,
      numOfWithdrawals: number | string,
      submission: string | number[]
    ): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
