/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IRollUpable extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): IRollUpable;
  methods: {
    newProofOfUTXORollUp(
      startingRoot: number | string,
      startingIndex: number | string,
      initialSiblings: (number | string)[]
    ): TransactionObject<void>;

    newProofOfNullifierRollUp(
      prevRoot: string | number[]
    ): TransactionObject<void>;

    newProofOfWithdrawalRollUp(
      startingRoot: number | string,
      startingIndex: number | string
    ): TransactionObject<void>;

    updateProofOfUTXORollUp(
      id: number | string,
      leaves: (number | string)[]
    ): TransactionObject<void>;

    updateProofOfNullifierRollUp(
      id: number | string,
      leaves: (string | number[])[],
      siblings: (string | number[])[][]
    ): TransactionObject<void>;

    updateProofOfWithdrawalRollUp(
      id: number | string,
      initialSiblings: (number | string)[],
      leaves: (number | string)[]
    ): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
