/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class ITxChallenge extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)
  clone(): ITxChallenge
  methods: {
    challengeInclusion(
      txIndex: number | string,
      inflowIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeTransaction(
      txIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeAtomicSwap(
      txIndex: number | string,
      blockData: string | number[],
    ): TransactionObject<void>

    challengeUsedNullifier(
      txIndex: number | string,
      inflowIndex: number | string,
      sibling: (string | number[])[],
      blockData: string | number[],
    ): TransactionObject<void>

    challengeDuplicatedNullifier(
      nullifier: string | number[],
      blockData: string | number[],
    ): TransactionObject<void>

    isValidRef(
      l2BlockHash: string | number[],
      ref: number | string,
    ): TransactionObject<boolean>
  }
  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
