/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export interface ITxValidator extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ITxValidator
  clone(): ITxValidator
  methods: {
    validateInclusion(
      blockData: string | number[],
      txIndex: number | string | BN,
      inflowIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    isValidRef(
      l2BlockHash: string | number[],
      ref: number | string | BN,
    ): NonPayableTransactionObject<boolean>

    validateOutflow(
      blockData: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateAtomicSwap(
      blockData: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateUsedNullifier(
      blockData: string | number[],
      parentHeader: string | number[],
      txIndex: number | string | BN,
      inflowIndex: number | string | BN,
      sibling: (string | number[])[],
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateDuplicatedNullifier(
      blockData: string | number[],
      nullifier: string | number[],
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    validateSNARK(
      blockData: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>
  }
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
  }
}
