/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class SetupWizard extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): SetupWizard

  methods: {
    CHALLENGE_LIMIT(): TransactionObject<string>

    CHALLENGE_PERIOD(): TransactionObject<string>

    MINIMUM_STAKE(): TransactionObject<string>

    POOL_SIZE(): TransactionObject<string>

    REF_DEPTH(): TransactionObject<string>

    SUB_TREE_DEPTH(): TransactionObject<string>

    SUB_TREE_SIZE(): TransactionObject<string>

    deregister(): TransactionObject<void>

    finalize(arg0: string | number[]): TransactionObject<void>

    isProposable(proposerAddr: string): TransactionObject<boolean>

    propose(arg0: string | number[]): TransactionObject<void>

    proxied(arg0: string | number[]): TransactionObject<string>

    register(): TransactionObject<void>

    withdrawReward(amount: number | string): TransactionObject<void>

    registerVk(
      numOfInputs: number | string,
      numOfOutputs: number | string,
      alpha1: (number | string)[],
      beta2: (number | string)[][],
      gamma2: (number | string)[][],
      delta2: (number | string)[][],
      ic: (number | string)[][],
    ): TransactionObject<void>

    makeUserInteractable(addr: string): TransactionObject<void>

    makeRollUpable(addr: string): TransactionObject<void>

    makeChallengeable(
      depositChallenge: string,
      headerChallenge: string,
      migrationChallenge: string,
      rollUpChallenge: string,
      txChallenge: string,
    ): TransactionObject<void>

    makeMigratable(addr: string): TransactionObject<void>

    allowMigrants(migrants: string[]): TransactionObject<void>

    completeSetup(): TransactionObject<void>
  }

  events: {
    Finalized: ContractEvent<string>
    MassDepositCommit: ContractEvent<{
      id: string
      merged: string
      fee: string
      0: string
      1: string
      2: string
    }>
    NewProposal: ContractEvent<string>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
