/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class SNARK extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): SNARK

  methods: {
    verify(
      vk: {
        alpha1: { X: number | string; Y: number | string }
        beta2: { X: (number | string)[]; Y: (number | string)[] }
        gamma2: { X: (number | string)[]; Y: (number | string)[] }
        delta2: { X: (number | string)[]; Y: (number | string)[] }
        ic: { X: number | string; Y: number | string }[]
      },
      input: (number | string)[],
      proof: {
        a: { X: number | string; Y: number | string }
        b: { X: (number | string)[]; Y: (number | string)[] }
        c: { X: number | string; Y: number | string }
      },
    ): TransactionObject<boolean>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
