/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string
  newOwner: string
  0: string
  1: string
}>

export interface TxValidator extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): TxValidator
  clone(): TxValidator
  methods: {
    CHALLENGE_PERIOD(): NonPayableTransactionObject<string>

    MAX_BLOCK_SIZE(): NonPayableTransactionObject<string>

    MAX_UTXO(): NonPayableTransactionObject<string>

    MAX_VALIDATION_GAS(): NonPayableTransactionObject<string>

    MAX_WITHDRAWAL(): NonPayableTransactionObject<string>

    MINIMUM_STAKE(): NonPayableTransactionObject<string>

    NULLIFIER_TREE_DEPTH(): NonPayableTransactionObject<string>

    REF_DEPTH(): NonPayableTransactionObject<string>

    UTXO_SUB_TREE_DEPTH(): NonPayableTransactionObject<string>

    UTXO_SUB_TREE_SIZE(): NonPayableTransactionObject<string>

    UTXO_TREE_DEPTH(): NonPayableTransactionObject<string>

    WITHDRAWAL_SUB_TREE_DEPTH(): NonPayableTransactionObject<string>

    WITHDRAWAL_SUB_TREE_SIZE(): NonPayableTransactionObject<string>

    WITHDRAWAL_TREE_DEPTH(): NonPayableTransactionObject<string>

    allowedMigrants(arg0: string): NonPayableTransactionObject<boolean>

    consensusProvider(): NonPayableTransactionObject<string>

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>

    proxied(arg0: string | number[]): NonPayableTransactionObject<string>

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>

    validators(arg0: string | number[]): NonPayableTransactionObject<string>

    /**
     * Challenge when any of the used nullifier's inclusion reference is invalid.
     * @param  // blockData Serialized block data
     * @param inflowIndex Index of the inflow note in the tx.
     * @param txIndex Index of the transaction in the tx list of the block body.
     */
    validateInclusion(
      arg0: string | number[],
      txIndex: number | string | BN,
      inflowIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    /**
     * Each nullifier should be paired with an inclusion reference which is a root of      utxo tree. For the inclusion reference, You can use finalized roots or recent      blocks' utxo roots. When you use recent blocks' utxo roots, recent REF_DEPTH      of utxo roots are available. It costs maximum 1800*REF_DEPTH gas to validate      an inclusion reference during the TX challenge process.
     * It checks the validity of an inclusion refernce for a nullifier.
     * @param l2BlockHash Storage block's hash value where to start searching for.
     * @param ref Utxo root which includes the nullifier's origin utxo.
     */
    isValidRef(
      l2BlockHash: string | number[],
      ref: number | string | BN,
    ): NonPayableTransactionObject<boolean>

    /**
     * Challenge when the submitted transaction has an invalid outflow
     * @param  // blockData Serialized block data
     * @param txIndex Index of the transaction in the tx list of the block body.
     */
    validateOutflow(
      arg0: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    /**
     * Challenge when the submitted transaction does not follow correct atomic swap protocol
     * @param  // blockData Serialized block data
     * @param txIndex Index of the transaction in the tx list of the block body.
     */
    validateAtomicSwap(
      arg0: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    /**
     * Challenge when the block is trying to use an already used nullifier.
     * @param  // parentHeader  Serialized parent header data
     * @param inflowIndex Index of the inflow note in the tx.
     * @param sibling The sibling data of the nullifier.
     * @param txIndex Index of the transaction in the tx list of the block body.
     */
    validateUsedNullifier(
      arg0: string | number[],
      arg1: string | number[],
      txIndex: number | string | BN,
      inflowIndex: number | string | BN,
      sibling: (string | number[])[],
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    /**
     * Challenge when a nullifier used twice in a same block.
     * @param  // blockData Serialized block data
     * @param nullifier Double included nullifier.
     */
    validateDuplicatedNullifier(
      arg0: string | number[],
      nullifier: string | number[],
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>

    /**
     * Challenge when the submitted transaction has an invalid SNARK proof
     * @param  // blockData Serialized block data
     * @param txIndex Index of the transaction in the tx list of the block body.
     */
    validateSNARK(
      arg0: string | number[],
      txIndex: number | string | BN,
    ): NonPayableTransactionObject<{
      slash: boolean
      reason: string
      0: boolean
      1: string
    }>
  }
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>,
    ): EventEmitter

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
  }

  once(event: 'OwnershipTransferred', cb: Callback<OwnershipTransferred>): void
  once(
    event: 'OwnershipTransferred',
    options: EventOptions,
    cb: Callback<OwnershipTransferred>,
  ): void
}
