/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class UserInteractable extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)
  clone(): UserInteractable
  methods: {
    CHALLENGE_LIMIT(): TransactionObject<string>

    CHALLENGE_PERIOD(): TransactionObject<string>

    MINIMUM_STAKE(): TransactionObject<string>

    POOL_SIZE(): TransactionObject<string>

    RANGE_LIMIT(): TransactionObject<string>

    REF_DEPTH(): TransactionObject<string>

    SNARK_FIELD(): TransactionObject<string>

    SUB_TREE_DEPTH(): TransactionObject<string>

    SUB_TREE_SIZE(): TransactionObject<string>

    committedDeposits(
      massDepositHash: string | number[],
    ): TransactionObject<string>

    finalizedUTXOs(utxoRoot: string | number[]): TransactionObject<boolean>

    massDepositId(): TransactionObject<string>

    migrations(migrationHash: string | number[]): TransactionObject<boolean>

    parentOf(header: string | number[]): TransactionObject<string>

    proposals(
      proposalId: string | number[],
    ): TransactionObject<{
      header: string
      challengeDue: string
      slashed: boolean
      0: string
      1: string
      2: boolean
    }>

    proposers(
      addr: string,
    ): TransactionObject<{
      stake: string
      reward: string
      exitAllowance: string
      0: string
      1: string
      2: string
    }>

    snapshotTimestamp(): TransactionObject<string>

    stagedDeposits(): TransactionObject<{
      merged: string
      fee: string
      0: string
      1: string
    }>

    stagedSize(): TransactionObject<string>

    utxoRootOf(header: string | number[]): TransactionObject<string>

    withdrawables(
      idx: number | string,
    ): TransactionObject<{
      root: string
      index: string
      0: string
      1: string
    }>

    withdrawn(leaf: string | number[]): TransactionObject<boolean>

    deposit(
      eth: number | string,
      salt: number | string,
      token: string,
      amount: number | string,
      nft: number | string,
      pubKey: (number | string)[],
      fee: number | string,
    ): TransactionObject<void>

    withdraw(
      eth: number | string,
      token: string,
      amount: number | string,
      nft: number | string,
      fee: number | string,
      rootIndex: number | string,
      leafIndex: number | string,
      siblings: (number | string)[],
    ): TransactionObject<void>

    withdrawUsingSignature(
      to: string,
      eth: number | string,
      token: string,
      amount: number | string,
      nft: number | string,
      fee: number | string,
      rootIndex: number | string,
      leafIndex: number | string,
      siblings: (number | string)[],
      v: number | string,
      r: string | number[],
      s: string | number[],
    ): TransactionObject<void>
  }
  events: {
    Deposit: ContractEvent<{
      queuedAt: string
      note: string
      fee: string
      0: string
      1: string
      2: string
    }>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
