/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class UtxoTreeTester extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): UtxoTreeTester

  methods: {
    append(
      startingRoot: number | string,
      index: number | string,
      leaves: (number | string)[],
      initialSiblings: (number | string)[],
    ): TransactionObject<string>

    merkleProof(
      root: number | string,
      leaf: number | string,
      index: number | string,
      siblings: (number | string)[],
    ): TransactionObject<boolean>

    appendSubTree(
      startingRoot: number | string,
      index: number | string,
      subTreeDepth: number | string,
      leaves: (number | string)[],
      subTreeSiblings: (number | string)[],
    ): TransactionObject<string>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
