export const TxChallengeABI = [
  {
    inputs: [],
    name: 'CHALLENGE_PERIOD',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_UTXO',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_WITHDRAWAL',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MINIMUM_STAKE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NULLIFIER_TREE_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'REF_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'UTXO_SUB_TREE_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'UTXO_SUB_TREE_SIZE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'UTXO_TREE_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WITHDRAWAL_SUB_TREE_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WITHDRAWAL_SUB_TREE_SIZE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WITHDRAWAL_TREE_DEPTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'allowedMigrants',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'massDepositHash', type: 'bytes32' },
    ],
    name: 'committedDeposits',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'utxoRoot', type: 'bytes32' }],
    name: 'finalizedUTXORoots',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'genesis',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'numOfInputs', type: 'uint8' },
      { internalType: 'uint8', name: 'numOfOutputs', type: 'uint8' },
    ],
    name: 'getVk',
    outputs: [
      { internalType: 'uint256[2]', name: 'alfa1', type: 'uint256[2]' },
      { internalType: 'uint256[2][2]', name: 'beta2', type: 'uint256[2][2]' },
      { internalType: 'uint256[2][2]', name: 'gamma2', type: 'uint256[2][2]' },
      { internalType: 'uint256[2][2]', name: 'delta2', type: 'uint256[2][2]' },
      { internalType: 'uint256[2][]', name: 'ic', type: 'uint256[2][]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'latest',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'massDepositId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'migrationHash', type: 'bytes32' },
    ],
    name: 'migrations',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'header', type: 'bytes32' }],
    name: 'parentOf',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'proposalId', type: 'bytes32' }],
    name: 'proposals',
    outputs: [
      { internalType: 'bytes32', name: 'header', type: 'bytes32' },
      { internalType: 'uint256', name: 'challengeDue', type: 'uint256' },
      { internalType: 'bool', name: 'slashed', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proposedBlocks',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'addr', type: 'address' }],
    name: 'proposers',
    outputs: [
      { internalType: 'uint256', name: 'stake', type: 'uint256' },
      { internalType: 'uint256', name: 'reward', type: 'uint256' },
      { internalType: 'uint256', name: 'exitAllowance', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registeredERC20s',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registeredERC721s',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stagedDeposits',
    outputs: [
      { internalType: 'bytes32', name: 'merged', type: 'bytes32' },
      { internalType: 'uint256', name: 'fee', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stagedSize',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'header', type: 'bytes32' }],
    name: 'utxoRootOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'header', type: 'bytes32' }],
    name: 'withdrawalRootOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'leaf', type: 'bytes32' }],
    name: 'withdrawn',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'txIndex', type: 'uint256' },
      { internalType: 'bytes', name: 'blockData', type: 'bytes' },
    ],
    name: 'challengeSNARK',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: 'uint256',
                name: 'inclusionRoot',
                type: 'uint256',
              },
              { internalType: 'bytes32', name: 'nullifier', type: 'bytes32' },
            ],
            internalType: 'struct Inflow[]',
            name: 'inflow',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'note', type: 'uint256' },
              { internalType: 'uint8', name: 'outflowType', type: 'uint8' },
              {
                components: [
                  { internalType: 'address', name: 'to', type: 'address' },
                  { internalType: 'uint256', name: 'eth', type: 'uint256' },
                  { internalType: 'address', name: 'token', type: 'address' },
                  { internalType: 'uint256', name: 'amount', type: 'uint256' },
                  { internalType: 'uint256', name: 'nft', type: 'uint256' },
                  { internalType: 'uint256', name: 'fee', type: 'uint256' },
                ],
                internalType: 'struct PublicData',
                name: 'publicData',
                type: 'tuple',
              },
            ],
            internalType: 'struct Outflow[]',
            name: 'outflow',
            type: 'tuple[]',
          },
          { internalType: 'uint256', name: 'swap', type: 'uint256' },
          { internalType: 'uint256', name: 'fee', type: 'uint256' },
          {
            components: [
              {
                components: [
                  { internalType: 'uint256', name: 'X', type: 'uint256' },
                  { internalType: 'uint256', name: 'Y', type: 'uint256' },
                ],
                internalType: 'struct G1Point',
                name: 'a',
                type: 'tuple',
              },
              {
                components: [
                  { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
                  { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
                ],
                internalType: 'struct G2Point',
                name: 'b',
                type: 'tuple',
              },
              {
                components: [
                  { internalType: 'uint256', name: 'X', type: 'uint256' },
                  { internalType: 'uint256', name: 'Y', type: 'uint256' },
                ],
                internalType: 'struct G1Point',
                name: 'c',
                type: 'tuple',
              },
            ],
            internalType: 'struct Proof',
            name: 'proof',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'memo', type: 'bytes' },
        ],
        internalType: 'struct Transaction',
        name: 'transaction',
        type: 'tuple',
      },
    ],
    name: 'hasValidSNARK',
    outputs: [
      { internalType: 'bool', name: 'result', type: 'bool' },
      { internalType: 'string', name: 'reason', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
